(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAIIAAgPIALAAIAAAPg");
	this.shape.setTransform(114.55,-59.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRBBQgIgDgFgEQgFgEgCgFQgCgFgBgEIAMAAQABAFADAEIAHAFQADACAFABIAJAAQAKAAAHgDQAGgEAEgGQADgGABgIIABgQQgGAIgIAFQgKAEgIAAQgLAAgIgDQgIgFgFgHQgFgGgDgJQgCgIAAgKQAAgKACgJQADgJAFgGQAFgHAIgEQAIgEALAAIAJABIAJAEIAIAGQADADACAFIABAAIAAgRIALAAIAABUQAAAKgCAIQgCAJgFAGQgFAGgIAFQgJADgMAAQgLAAgGgCgAgLg1QgGACgEAEQgFAFgCAHQgCAHgBAIQABAJABAIQACAGAEAHQAEAFAGAEQAGADAIAAQAHAAAFgDQAHgEADgFQAEgFADgGQACgIAAgHQAAgIgCgIQgCgHgEgFQgEgGgGgDQgGgDgHAAQgHAAgFADg");
	this.shape_1.setTransform(106.4,-61.55);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgFgGQgGgGgNAAQgEAAgEABQgEACgDADIgHAGIgDAGIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgEQAHgFAJAAQAIAAAIADQAIADAFAIQACAFABAFIABALIAAA8g");
	this.shape_2.setTransform(96.1,-63.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgFBBIAAhdIALAAIAABdgAgFgwIAAgQIALAAIAAAQg");
	this.shape_3.setTransform(89.15,-65.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgFgGQgGgGgNAAQgEAAgEABQgEACgDADIgHAGIgDAGIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgEQAHgFAJAAQAIAAAIADQAIADAFAIQACAFABAFIABALIAAA8g");
	this.shape_4.setTransform(82.15,-63.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgEQAHgFAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAPIAAAtg");
	this.shape_5.setTransform(74.625,-63.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAQgGAAgGgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_6.setTransform(66.425,-63.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgRAuQgJgEgFgHQgFgGgCgJQgDgJAAgKQAAgKADgJQADgJAGgHQAFgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhHAAQAAAHACAHQABAHAEAFQAFAFAGADQAFADAHAAQAKAAAIgGQAHgGADgKIAMAAQgBAHgEAFQgDAGgFAEQgFAFgGACQgHACgJAAQgKAAgIgDgAAegFQAAgHgCgGQgCgGgDgFQgDgEgHgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgCAGIgDANIA7AAIAAAAg");
	this.shape_7.setTransform(56.2,-63.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFBBIAAiBIAKAAIAACBg");
	this.shape_8.setTransform(49.25,-65.125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgFgGQgGgGgNAAQgEAAgEABQgEACgDADIgHAGIgDAGIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgEQAHgFAJAAQAJAAAHADQAIADAFAIQACAFABAFIABALIAAA8g");
	this.shape_9.setTransform(37.25,-63.45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQAuQgIgDgGgGQgGgGgDgJQgDgKAAgMQAAgJACgJQADgJAFgHQAGgGAIgEQAIgEAKAAQALAAAIAEQAIAEAFAGQAGAHACAJQADAJAAAJQAAALgDAJQgDAJgGAHQgFAGgIAEQgIADgKAAQgIAAgIgDgAgOgjQgGADgDAGQgEAFgCAHIgCAOQAAAJACAHQACAHAEAGQAEAFAGADQAGADAHAAQAIAAAGgEQAGgDAEgGQAEgFACgHQABgHAAgIQAAgHgBgHQgCgIgEgFQgEgFgGgDQgGgDgIAAQgIAAgGADg");
	this.shape_10.setTransform(27.275,-63.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgFBBIAAhdIALAAIAABdgAgFgwIAAgQIALAAIAAAQg");
	this.shape_11.setTransform(20.3,-65.125);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgDA5QgEgEAAgLIAAhDIgNAAIAAgJIANAAIAAgaIAKAAIAAAaIASAAIAAAJIgSAAIAAA/IAAAGIABAEQABAAAAABQAAAAAAAAQABABAAAAQABAAAAAAIAGABIAEAAIAEgBIAAAJIgFABIgHABQgJAAgDgEg");
	this.shape_12.setTransform(15.75,-64.475);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAQgGAAgGgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_13.setTransform(8.525,-63.325);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgEQAHgFAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAPIAAAtg");
	this.shape_14.setTransform(0.775,-63.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgSAuQgIgEgFgHQgFgGgDgJQgCgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQAAAHACAHQACAHAEAFQAFAFAFADQAGADAHAAQALAAAHgGQAIgGACgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQAAgHgCgGQgCgGgEgFQgEgEgGgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgDANIA9AAIAAAAg");
	this.shape_15.setTransform(-7.65,-63.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgFgGQgGgGgNAAQgEAAgEABQgEACgDADIgHAGIgDAGIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgEQAHgFAJAAQAJAAAHADQAIADAEAIQADAFABAFIABALIAAA8g");
	this.shape_16.setTransform(-17.65,-63.45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgSAuQgHgEgFgHQgGgGgCgJQgDgJAAgKQAAgKADgJQADgJAGgHQAFgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhHAAQAAAHABAHQACAHAFAFQADAFAHADQAFADAHAAQAKAAAIgGQAHgGADgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQAAgHgDgGQgBgGgEgFQgEgEgFgDQgGgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgCANIA8AAIAAAAg");
	this.shape_17.setTransform(-27.65,-63.325);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgRBBQgIgDgEgEQgGgEgCgFQgDgFAAgEIAMAAQABAFADAEIAHAFQADACAFABIAJAAQAKAAAHgDQAGgEAEgGQADgGABgIIABgQQgFAIgJAFQgJAEgJAAQgLAAgIgDQgHgFgGgHQgFgGgDgJQgCgIAAgKQAAgKACgJQADgJAFgGQAFgHAIgEQAIgEALAAIAJABIAJAEIAIAGQADADACAFIABAAIAAgRIALAAIAABUQAAAKgCAIQgCAJgFAGQgFAGgIAFQgJADgMAAQgKAAgHgCgAgLg1QgGACgEAEQgFAFgCAHQgDAHAAAIQAAAJACAIQACAGAEAHQAEAFAGAEQAGADAHAAQAIAAAFgDQAGgEAFgFQAEgFACgGQACgIAAgHQAAgIgCgIQgCgHgEgFQgEgGgGgDQgGgDgIAAQgFAAgGADg");
	this.shape_18.setTransform(-38.3,-61.55);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgCA5QgFgEAAgLIAAhDIgNAAIAAgJIANAAIAAgaIAKAAIAAAaIARAAIAAAJIgRAAIAAA/IAAAGIACAEQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIAGABIAEAAIAEgBIAAAJIgFABIgHABQgJAAgCgEg");
	this.shape_19.setTransform(140.55,-86.475);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAcAvIgcgpIgbApIgOAAIAkgwIghgtIANAAIAZAmIAbgmIANAAIghAtIAjAwg");
	this.shape_20.setTransform(133.6,-85.325);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgSAuQgHgEgFgHQgGgGgCgJQgDgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQAAAHACAHQADAHAEAFQAEAFAFADQAGADAHAAQAKAAAIgGQAIgGACgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQAAgHgCgGQgDgGgDgFQgEgEgFgDQgGgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgDANIA9AAIAAAAg");
	this.shape_21.setTransform(124.1,-85.325);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgFgFQgGgHgNAAQgEAAgEABQgEACgDACIgHAGIgDAHIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgFQAHgEAJAAQAIAAAIADQAIADAFAHQACAFABAGIABALIAAA8g");
	this.shape_22.setTransform(114.1,-85.45);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgPAvQgHgDgEgEQgFgEgCgGQgCgGgBgGIALAAQADAMAGAFQAHAFALAAQAGAAAFgCIAGgEQAEgCABgDQABgDAAgEQAAgHgEgDQgFgDgGgCIgNgDIgPgEQgHgCgEgFQgFgFAAgJQAAgMAJgIQAIgHAQAAQAPAAAJAHQAJAGACAQIgLAAQgBgLgHgEQgGgEgKAAQgKAAgGAEQgFAEAAAIQAAAGAEADQAFAEAGACIAOADIAPAEQAGADAFAFQADAFAAAJQABAHgDAFQgDAFgFADQgFAEgHACQgHABgHAAQgJAAgGgCg");
	this.shape_23.setTransform(99.6,-85.325);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgFQAHgEAMAAIAAAMQgJAAgGADQgGADgDAFQgDAFgCAIIgBANIAAAug");
	this.shape_24.setTransform(92.575,-85.45);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgSAuQgIgEgFgHQgFgGgDgJQgCgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQAAAHACAHQACAHAFAFQAEAFAFADQAGADAHAAQALAAAHgGQAIgGACgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQAAgHgCgGQgCgGgEgFQgEgEgGgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgDANIA9AAIAAAAg");
	this.shape_25.setTransform(84.15,-85.325);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAVAvIgVhOIgUBOIgNAAIgdhdIAMAAIAXBPIAWhPIALAAIAVBOIAYhOIALAAIgeBdg");
	this.shape_26.setTransform(72.7,-85.325);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgQAuQgIgDgGgGQgGgGgDgJQgDgKAAgMQAAgJACgJQADgJAFgHQAGgGAIgEQAIgEAKAAQALAAAIAEQAIAEAFAGQAGAHACAJQADAJAAAJQAAALgDAJQgDAJgGAHQgFAGgIAEQgIADgKAAQgIAAgIgDgAgOgjQgGADgDAGQgEAFgCAHIgCAOQAAAJACAHQACAHAEAGQAEAFAGADQAGADAHAAQAIAAAGgEQAGgDAEgGQAEgFACgHQABgHAAgIQAAgHgBgHQgCgIgEgFQgEgFgGgDQgGgDgIAAQgIAAgGADg");
	this.shape_27.setTransform(61.225,-85.325);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgqBCIAAiBIALAAIAAARIAAAAQACgFAFgDIAIgGIAJgEIAIgBQALAAAIAEQAIAEAFAGQAFAHACAJQADAJAAAKQAAAKgDAIQgCAJgGAGQgFAHgHAEQgIAEgKAAQgKAAgIgEQgKgFgFgIIAAAzgAgNg0QgGADgEAFQgEAFgCAIQgCAHAAAJQAAAHACAIQADAGADAFQAFAFAFADQAGAEAHAAQAIAAAGgEQAHgDADgGQAEgGACgGQACgIgBgJQABgJgDgGQgDgHgEgFQgEgEgGgDQgGgCgGAAQgHAAgGADg");
	this.shape_28.setTransform(50.95,-83.625);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgPAvQgGgDgFgEQgEgEgDgGQgCgGAAgGIAKAAQADAMAHAFQAGAFALAAQAGAAAEgCIAIgEQACgCABgDQACgDAAgEQAAgHgEgDQgFgDgGgCIgOgDIgOgEQgHgCgEgFQgEgFAAgJQAAgMAIgIQAJgHAPAAQAOAAAKAHQAJAGACAQIgLAAQgBgLgHgEQgHgEgJAAQgKAAgFAEQgGAEAAAIQAAAGAFADQAEAEAHACIANADIAOAEQAHADAEAFQAFAFAAAJQgBAHgCAFQgDAFgFADQgFAEgHACQgHABgHAAQgJAAgGgCg");
	this.shape_29.setTransform(35.75,-85.325);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgPAvQgGgDgFgEQgEgEgDgGQgCgGAAgGIAKAAQADAMAHAFQAGAFALAAQAGAAAEgCIAIgEQACgCABgDQACgDAAgEQAAgHgEgDQgFgDgGgCIgOgDIgOgEQgHgCgEgFQgEgFAAgJQAAgMAIgIQAJgHAPAAQAOAAAKAHQAJAGACAQIgLAAQgBgLgHgEQgHgEgJAAQgKAAgFAEQgGAEAAAIQAAAGAFADQAEAEAHACIANADIAOAEQAHADAEAFQAFAFAAAJQgBAHgCAFQgDAFgFADQgFAEgHACQgHABgHAAQgJAAgGgCg");
	this.shape_30.setTransform(26.75,-85.325);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgSAuQgHgEgFgHQgGgGgCgJQgDgJAAgKQAAgKADgJQADgJAGgHQAFgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhHAAQAAAHABAHQACAHAFAFQADAFAHADQAFADAHAAQALAAAHgGQAHgGADgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQgBgHgCgGQgCgGgDgFQgEgEgFgDQgGgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgCANIA8AAIAAAAg");
	this.shape_31.setTransform(17.25,-85.325);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgGgFQgFgHgNAAQgEAAgEABQgFACgDACIgFAGIgEAHIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgFQAHgEAJAAQAJAAAHADQAHADAGAHQACAFABAGIABALIAAA8g");
	this.shape_32.setTransform(7.25,-85.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgFBBIAAhdIAKAAIAABdgAgFgwIAAgQIALAAIAAAQg");
	this.shape_33.setTransform(0.3,-87.125);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgPAvQgHgDgEgEQgEgEgDgGQgCgGAAgGIAKAAQADAMAHAFQAGAFALAAQAGAAAEgCIAIgEQACgCABgDQACgDAAgEQAAgHgEgDQgEgDgHgCIgOgDIgOgEQgHgCgEgFQgFgFABgJQAAgMAIgIQAJgHAPAAQAOAAAKAHQAJAGACAQIgLAAQgBgLgHgEQgHgEgJAAQgKAAgFAEQgGAEAAAIQAAAGAFADQAEAEAHACIANADIAOAEQAHADAEAFQAFAFAAAJQAAAHgDAFQgDAFgFADQgFAEgHACQgHABgHAAQgJAAgGgCg");
	this.shape_34.setTransform(-6.2,-85.325);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgSAuQgHgDgEgFQgEgFgCgGQgBgGAAgIIAAg8IAKAAIAAA8QAAAMAHAHQAFAGANAAQAFAAAFgCQAGgDADgFQAEgEACgHQACgGAAgIIAAgyIALAAIAABdIgLAAIAAgOIgFAGIgGAFIgIADQgFACgFAAQgKAAgFgCg");
	this.shape_35.setTransform(-15.7,-85.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgvBBIAAiBIAvAAQAKAAAJACQAIADAFAEQAFAEACAHQADAGAAAHQAAAHgCAEQgCAGgDADIgGAFIgIADIAAAAQANACAHAIQAHAIAAANQAAAKgEAHQgDAHgFAFQgGAEgIACQgIACgJAAgAgiA2IAfAAIAQgBQAIAAAFgDQAEgDADgFQACgFAAgJQAAgIgCgFQgDgFgFgCQgFgDgHgBIgPgBIggAAgAgigHIAeAAQAJAAAHgBQAGgCAEgDQAEgDACgFQABgEAAgGQAAgGgCgFQgCgEgEgCQgEgDgHgBIgQgBIgcAAg");
	this.shape_36.setTransform(-26.475,-87.125);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAdAvIgcgpIgdApIgNAAIAkgwIghgtIAOAAIAYAmIAbgmIANAAIgiAtIAjAwg");
	this.shape_37.setTransform(-42.2,-85.325);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgQAuQgIgDgGgGQgGgGgDgJQgDgKAAgMQAAgJACgJQADgJAFgHQAGgGAIgEQAIgEAKAAQALAAAIAEQAIAEAFAGQAGAHACAJQADAJAAAJQAAALgDAJQgDAJgGAHQgFAGgIAEQgIADgKAAQgIAAgIgDgAgOgjQgGADgDAGQgEAFgCAHIgCAOQAAAJACAHQACAHAEAGQAEAFAGADQAGADAHAAQAIAAAGgEQAGgDAEgGQAEgFACgHQABgHAAgIQAAgHgBgHQgCgIgEgFQgEgFgGgDQgGgDgIAAQgIAAgGADg");
	this.shape_38.setTransform(-51.675,-85.325);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgZA/QgKgGgHgJQgGgKgEgMQgDgMAAgOQAAgSAFgNQAEgMAIgJQAJgIAKgEQAMgDAMAAQAKAAAIACQAJADAGAFQAGAFAFAIQAEAIABAKIgMAAQgEgRgKgHQgKgHgRAAQgLAAgIAFQgIAFgGAHQgGAIgCALQgDAKAAALQABAKACALQACAKAFAIQAFAJAJAFQAJAFANAAQAIAAAGgDQAHgDAGgEQAFgFADgHQADgGACgIIANAAQgCAJgEAJQgEAIgHAGQgHAHgJADQgKAEgNAAQgOAAgLgFg");
	this.shape_39.setTransform(-63.2,-87.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt3, new cjs.Rectangle(-88.2,-96.5,250,44), null);


(lib.txt2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAIIAAgPIALAAIAAAPg");
	this.shape.setTransform(350.2,-63.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPAvQgGgDgFgEQgEgEgDgGQgDgGABgGIAKAAQADAMAGAFQAHAFALAAQAGAAAEgCIAHgEQADgCABgDQACgDAAgEQAAgHgEgDQgFgDgGgCIgOgDIgOgEQgHgCgEgFQgEgFgBgJQABgMAIgIQAJgHAPAAQAOAAAKAHQAKAGABAQIgLAAQgBgLgHgEQgGgEgKAAQgKAAgFAEQgGAEAAAIQAAAGAFADQAEAEAGACIAOADIAOAEQAHADAEAFQAFAFAAAJQgBAHgCAFQgDAFgFADQgFAEgHACQgHABgHAAQgIAAgHgCg");
	this.shape_1.setTransform(343.2,-67.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgDA5QgEgEAAgLIAAhDIgNAAIAAgJIANAAIAAgaIAKAAIAAAaIASAAIAAAJIgSAAIAAA/IAAAGIACAEQAAAAAAABQAAAAAAAAQABABAAAAQABAAAAAAIAGABIAEAAIAEgBIAAAJIgFABIgHABQgJAAgDgEg");
	this.shape_2.setTransform(336.15,-68.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgPAvQgHgDgEgEQgFgEgCgGQgCgGgBgGIALAAQADAMAGAFQAHAFALAAQAGAAAFgCIAGgEQAEgCABgDQABgDAAgEQAAgHgEgDQgFgDgGgCIgNgDIgPgEQgHgCgEgFQgFgFAAgJQAAgMAJgIQAIgHAQAAQAPAAAJAHQAJAGACAQIgLAAQgBgLgHgEQgHgEgJAAQgKAAgGAEQgFAEAAAIQAAAGAEADQAFAEAGACIAOADIAPAEQAGADAFAFQADAFAAAJQAAAHgCAFQgDAFgFADQgFAEgHACQgHABgHAAQgJAAgGgCg");
	this.shape_3.setTransform(329.2,-67.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSAuQgHgDgEgFQgDgEgCgHQgCgGAAgIIAAg8IALAAIAAA8QAAAMAFAHQAGAGAMABQAGAAAGgDQAFgDAEgEQADgGACgGQACgGAAgIIAAgyIALAAIAABdIgLAAIAAgOIgFAGIgGAEIgIAFQgFABgFAAQgKAAgFgCg");
	this.shape_4.setTransform(319.7,-66.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAwIAAhcIALAAIAAARQAFgLAGgFQAHgEAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAOIAAAug");
	this.shape_5.setTransform(312.175,-67.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgDA5QgEgEAAgLIAAhDIgNAAIAAgJIANAAIAAgaIAKAAIAAAaIARAAIAAAJIgRAAIAAA/IAAAGIABAEQABAAAAABQAAAAAAAAQABABAAAAQABAAAAAAIAFABIAFAAIAEgBIAAAJIgFABIgHABQgIAAgEgEg");
	this.shape_6.setTransform(306.2,-68.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTA/QgIgFgFgGQgFgHgCgIQgDgJAAgLQAAgKADgIQACgIAFgHQAFgHAIgEQAIgEAKgBQAJABAJAEQAKAEAFAJIAAgzIALAAIAACBIgLAAIAAgRIAAAAQgCAFgFAEQgDADgFACIgJAEIgIABQgLAAgIgDgAgNgSQgGADgEAGQgEAFgCAHQgBAIAAAJQAAAIACAIQADAGAEAFQAEAFAGACQAGACAFABQAIgBAGgDQAGgDAEgFQAEgFACgIQACgHAAgJQAAgIgCgGQgCgHgEgFQgFgFgFgEQgGgDgIAAQgHABgGADg");
	this.shape_7.setTransform(293.1,-68.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgMgFgHQgGgGgNAAQgEAAgEACQgFABgDACIgGAHIgDAGIgCAJIAAAJIAAAxIgLAAIAAhcIALAAIAAANQAGgHAHgFQAHgEAJAAQAIAAAIADQAIADAEAHQAEAFABAGIAAALIAAA8g");
	this.shape_8.setTransform(282.8,-67.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAIgMgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_9.setTransform(273.025,-67.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgEBBIAAiBIAJAAIAACBg");
	this.shape_10.setTransform(265.85,-68.875);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgSBAQgHgCgFgEQgEgEgDgFQgDgEABgFIALAAQACAGACADIAGAFQAEACAEAAIAKABQAKAAAGgDQAIgEACgGQAEgHABgHIABgQQgFAJgKAEQgIAFgKgBQgKAAgIgEQgHgEgGgGQgFgHgCgJQgDgIAAgKQAAgKADgJQACgJAFgHQAFgGAIgEQAIgEALAAIAIACIAJADIAIAGQAFADACAFIAAAAIAAgQIALAAIAABTQAAAJgCAJQgCAIgFAHQgFAHgIADQgIAEgNAAQgKAAgIgDgAgLg1QgGACgEAFQgEAEgDAHQgDAHABAJQgBAIACAIQACAHAEAFQAEAGAGADQAGAEAHAAQAIAAAGgEQAFgCAEgGQAEgFADgGQACgHAAgIQAAgJgCgHQgCgIgEgEQgEgGgGgDQgGgDgIAAQgFAAgGADg");
	this.shape_11.setTransform(258.2,-65.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgMgGgHQgFgGgNAAQgEAAgEACQgEABgEACIgFAHIgEAGIgCAJIAAAJIAAAxIgLAAIAAhcIALAAIAAANQAGgHAHgFQAHgEAJAAQAJAAAHADQAHADAGAHQADAFABAGIAAALIAAA8g");
	this.shape_12.setTransform(247.9,-67.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrBBIAAiBIBVAAIAAALIhJAAIAAAuIBCAAIAAAKIhCAAIAAAzIBLAAIAAALg");
	this.shape_13.setTransform(237.8,-68.875);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAVAvIgVhOIgUBOIgNAAIgchdIALAAIAXBPIAWhPIALAAIAVBOIAYhOIALAAIgeBdg");
	this.shape_14.setTransform(220.5,-67.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgRAuQgIgEgGgHQgFgGgDgJQgCgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQAAAHADAHQACAHADAFQAFAFAFADQAGADAHAAQALAAAHgGQAIgGACgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgGACQgHACgJAAQgKAAgIgDgAAegFQAAgHgBgGQgCgGgEgFQgDgEgHgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgCAGIgEANIA8AAIAAAAg");
	this.shape_15.setTransform(209,-67.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAlBBIhKhwIAAAAIAABwIgNAAIAAiBIAOAAIBKBwIABAAIAAhwIAMAAIAACBg");
	this.shape_16.setTransform(197.525,-68.875);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAaBBIgig0IgSARIAAAjIgLAAIAAiBIALAAIAABQIAtgsIAPAAIgiAhIAmA8g");
	this.shape_17.setTransform(182.025,-68.875);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUAwIAAhcIALAAIAAARQAFgLAGgFQAHgEAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAOIAAAug");
	this.shape_18.setTransform(174.525,-67.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgQAuQgIgDgGgGQgGgGgDgJQgDgKAAgMQAAgJACgJQADgJAFgHQAGgGAIgEQAIgEAKAAQALAAAIAEQAIAEAFAGQAGAHACAJQADAJAAAJQAAALgDAJQgDAJgGAHQgFAGgIAEQgIADgKAAQgIAAgIgDgAgOgjQgGADgDAGQgEAFgCAHIgCAOQAAAJACAHQACAHAEAGQAEAFAGADQAGADAHAAQAIAAAGgEQAGgDAEgGQAEgFACgHQABgHAAgIQAAgHgBgHQgCgIgEgFQgEgFgGgDQgGgDgIAAQgIAAgGADg");
	this.shape_19.setTransform(166.125,-67.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAUAvIgUhOIgUBOIgNAAIgchdIAKAAIAZBPIAVhPIAMAAIAUBOIAZhOIALAAIgfBdg");
	this.shape_20.setTransform(154.65,-67.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgCA5QgFgEAAgLIAAhDIgNAAIAAgJIANAAIAAgaIAKAAIAAAaIASAAIAAAJIgSAAIAAA/IAAAGIACAEQAAAAAAABQAAAAAAAAQABABAAAAQABAAAAAAIAGABIAEAAIAEgBIAAAJIgFABIgHABQgJAAgCgEg");
	this.shape_21.setTransform(145.6,-68.225);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgSAuQgIgEgEgHQgGgGgDgJQgCgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQAAAHACAHQACAHAEAFQAFAFAFADQAGADAHAAQALAAAHgGQAIgGACgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQAAgHgCgGQgCgGgEgFQgEgEgFgDQgGgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgDANIA9AAIAAAAg");
	this.shape_22.setTransform(138.15,-67.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgMgFgHQgGgGgNAAQgEAAgEACQgEABgDACIgHAHIgDAGIgCAJIgBAJIAAAxIgKAAIAAhcIAKAAIAAANQAHgHAHgFQAHgEAJAAQAJAAAHADQAIADAEAHQADAFABAGIABALIAAA8g");
	this.shape_23.setTransform(128.15,-67.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAIgMgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_24.setTransform(113.375,-67.075);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AA1AwIAAhAQAAgKgFgFQgEgGgMAAQgGAAgFADQgGACgEAGIgCAFIgCAGIgCAIIAAAGIAAAxIgKAAIAAhAQABgKgFgFQgEgGgLAAQgGAAgGADQgFACgEAGIgEAFIgCAGIgBAIIAAAGIAAAxIgKAAIAAhcIAKAAIAAAOQAFgJAHgEQAJgEAIAAQAHAAAEACQAFABADACIAFAGIADAHQAEgJAJgFQAHgEAKAAQAKAAAFAEQAGACADAGQADAFACAGIABAOIAAA6g");
	this.shape_25.setTransform(95.7,-67.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgQAuQgIgDgGgGQgGgGgDgJQgDgKAAgMQAAgJACgJQADgJAFgHQAGgGAIgEQAIgEAKAAQALAAAIAEQAIAEAFAGQAGAHACAJQADAJAAAJQAAALgDAJQgDAJgGAHQgFAGgIAEQgIADgKAAQgIAAgIgDgAgOgjQgGADgDAGQgEAFgCAHIgCAOQAAAJACAHQACAHAEAGQAEAFAGADQAGADAHAAQAIAAAGgEQAGgDAEgGQAEgFACgHQABgHAAgIQAAgHgBgHQgCgIgEgFQgEgFgGgDQgGgDgIAAQgIAAgGADg");
	this.shape_26.setTransform(83.225,-67.075);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgUAwIAAhcIALAAIAAARQAFgLAGgFQAHgEAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAOIAAAug");
	this.shape_27.setTransform(75.675,-67.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgGBCIAAhTIgOAAIAAgJIAOAAIAAgPQAAgLAEgHQAEgGALAAIAEAAIAEABIAAAKIgGgBQgEAAgCABQgDABgBADIgBAGIAAAGIAAAMIARAAIAAAJIgRAAIAABTg");
	this.shape_28.setTransform(69.725,-69);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(52,-78.2,316,22), null);


(lib.txt1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaBBIgig0IgSARIAAAjIgLAAIAAiBIALAAIAABQIAtgsIAPAAIgiAhIAmA8g");
	this.shape.setTransform(293.775,-89.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgFQAHgEAMAAIAAAMQgJAAgGADQgGADgDAFQgDAFgCAIIgBAOIAAAtg");
	this.shape_1.setTransform(286.275,-87.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQAuQgIgDgGgGQgGgGgDgJQgDgKAAgMQAAgJACgJQADgJAFgHQAGgGAIgEQAIgEAKAAQALAAAIAEQAIAEAFAGQAGAHACAJQADAJAAAJQAAALgDAJQgDAJgGAHQgFAGgIAEQgIADgKAAQgIAAgIgDgAgOgjQgGADgDAGQgEAFgCAHIgCAOQAAAJACAHQACAHAEAGQAEAFAGADQAGADAHAAQAIAAAGgEQAGgDAEgGQAEgFACgHQABgHAAgIQAAgHgBgHQgCgIgEgFQgEgFgGgDQgGgDgIAAQgIAAgGADg");
	this.shape_2.setTransform(277.875,-87.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAVAvIgVhOIgUBOIgNAAIgchdIALAAIAXBPIAWhPIALAAIAVBOIAYhOIALAAIgeBdg");
	this.shape_3.setTransform(266.4,-87.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgCA5QgFgEAAgLIAAhDIgNAAIAAgJIANAAIAAgaIAKAAIAAAaIARAAIAAAJIgRAAIAAA/IAAAGIABAEQABAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIAFABIAFAAIAEgBIAAAJIgFABIgHABQgIAAgDgEg");
	this.shape_4.setTransform(257.35,-88.975);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSAuQgHgEgFgHQgGgGgCgJQgDgJAAgKQAAgKADgJQADgJAGgHQAFgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhHAAQAAAHACAHQABAHAFAFQADAFAHADQAFADAHAAQALAAAHgGQAHgGADgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgGACQgHACgJAAQgKAAgJgDgAAfgFQgBgHgCgGQgCgGgDgFQgEgEgFgDQgGgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgCANIA8AAIAAAAg");
	this.shape_5.setTransform(249.9,-87.825);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgGgFQgFgHgNAAQgEAAgEABQgFACgDADIgFAFIgEAHIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgFQAHgEAJAAQAJAAAHADQAHADAGAHQACAGABAFIABALIAAA8g");
	this.shape_6.setTransform(239.9,-87.95);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgFQAHgEAMAAIAAAMQgJAAgGADQgGADgDAFQgDAFgCAIIgBAOIAAAtg");
	this.shape_7.setTransform(227.375,-87.95);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSAuQgHgEgFgHQgGgGgCgJQgDgJAAgKQAAgKADgJQADgJAGgHQAFgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhHAAQAAAHABAHQACAHAFAFQADAFAHADQAFADAHAAQAKAAAIgGQAHgGADgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQAAgHgDgGQgBgGgEgFQgEgEgFgDQgGgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgCANIA8AAIAAAAg");
	this.shape_8.setTransform(218.95,-87.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgIBAIgJgDQgEgCgDgEQgFgDgBgFIgBAAIAAAQIgLAAIAAiAIALAAIAAAzQAFgIAJgFQAKgFAJAAQAKAAAIAFQAIAEAEAGQAGAIADAJQACAIAAAJQAAAKgCAJQgDAKgFAGQgFAHgIADQgIAEgMAAIgIgCgAgMgSQgHADgDAFQgFAGgCAFQgCAHAAAJQAAAIACAIQACAGAEAGQAEAFAGADQAGAEAHgBQAHAAAFgCQAGgDAEgEQAFgFACgHQACgHABgJQAAgIgCgIQgCgGgEgGQgEgGgGgDQgGgDgIAAQgHAAgFADg");
	this.shape_9.setTransform(208.7,-89.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgEBBIAAhdIAJAAIAABdgAgFgwIAAgQIALAAIAAAQg");
	this.shape_10.setTransform(201.05,-89.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgGBCIAAhTIgOAAIAAgKIAOAAIAAgOQAAgLAEgGQAEgHALAAIAEAAIAEAAIAAAKIgGgBQgEABgCABQgDACgBACIgBAGIAAAGIAAALIARAAIAAAKIgRAAIAABTg");
	this.shape_11.setTransform(196.525,-89.75);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgSAuQgIgEgFgHQgFgGgDgJQgCgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQAAAHACAHQACAHAFAFQAEAFAFADQAGADAHAAQALAAAHgGQAIgGACgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQAAgHgCgGQgCgGgEgFQgEgEgGgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgDANIA9AAIAAAAg");
	this.shape_12.setTransform(184.05,-87.825);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgEBBIAAiBIAKAAIAACBg");
	this.shape_13.setTransform(177.1,-89.625);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgHBAIgJgDQgFgCgDgEQgEgDgDgFIAAAAIAAAQIgLAAIAAiAIALAAIAAAzQAFgIAKgFQAIgFAKAAQAKAAAIAFQAHAEAFAGQAGAIACAJQADAIAAAJQAAAKgDAJQgCAKgFAGQgFAHgIADQgIAEgLAAIgIgCgAgNgSQgGADgEAFQgDAGgDAFQgCAHAAAJQAAAIACAIQACAGAEAGQAEAFAGADQAGAEAHgBQAGAAAGgCQAGgDAEgEQAEgFADgHQADgHgBgJQABgIgCgIQgCgGgEgGQgEgGgGgDQgGgDgIAAQgHAAgGADg");
	this.shape_14.setTransform(169.85,-89.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAIgMgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_15.setTransform(159.375,-87.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgqBCIAAiBIALAAIAAARIAAAAQADgFADgDIAIgGIAKgEIAHgBQAMAAAIAEQAIAEAFAGQAFAHACAJQADAJAAAKQAAAKgDAIQgCAJgFAGQgGAHgIAEQgHAEgLAAQgJAAgJgEQgJgFgFgIIAAAzgAgNg0QgGADgEAFQgEAFgCAIQgCAHAAAJQAAAHACAIQACAGAEAFQAFAFAFADQAGAEAHAAQAIAAAGgEQAGgDAEgGQAEgGACgGQACgIgBgJQAAgJgCgGQgDgHgEgFQgEgEgGgDQgGgCgGAAQgHAAgGADg");
	this.shape_16.setTransform(148.9,-86.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAIgMgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_17.setTransform(138.425,-87.825);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgRAuQgIgEgGgHQgFgGgCgJQgDgJAAgLQAAgIAEgJQACgJAGgHQAFgHAIgEQAIgEAJAAQAQAAAKAIQALAIACAQIgLAAQgDgLgHgFQgHgGgLAAQgHAAgGADQgGAEgEAFQgEAGgBAHQgCAHAAAGQAAAIACAHQACAHADAFQAEAGAGADQAGAEAHAAQANAAAGgHQAIgHACgMIAMAAQgCAIgDAHQgEAGgEAFQgFAEgHADQgHACgJAAQgKAAgIgDg");
	this.shape_18.setTransform(128.2,-87.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgTA+QgIgEgFgGQgFgHgDgJQgCgJAAgKQAAgJACgJQADgJAFgHQAGgGAHgEQAIgFALABQAIgBAKAFQAIAEAGAJIAAgzIALAAIAACAIgLAAIAAgQIgBAAQgCAFgDADQgEAEgEACIgJADIgJACQgLAAgIgEgAgNgSQgGADgEAGQgEAFgCAIQgCAHAAAIQAAAKADAGQADAHAEAFQAEAEAGADQAFADAHAAQAHAAAGgEQAGgDAEgFQAEgGACgGQACgIAAgJQAAgHgCgIQgDgFgEgGQgDgFgHgEQgFgCgHAAQgIgBgGAEg");
	this.shape_19.setTransform(363,-110);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgFgGQgGgGgNAAQgEAAgEABQgEACgDADIgHAGIgDAGIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgEQAHgFAJAAQAJAAAHADQAIADAEAIQADAFABAFIABALIAAA8g");
	this.shape_20.setTransform(352.7,-108.45);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAQgGAAgGgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_21.setTransform(342.925,-108.325);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgSBBQgHgDgFgEQgEgEgDgFQgDgFABgEIALAAQACAFACAEIAGAFQAEACAEABIAKAAQAKAAAGgDQAIgEACgGQAEgGABgIIABgQQgFAIgKAFQgIAEgKAAQgKAAgIgDQgHgFgGgHQgFgGgCgJQgDgIAAgKQAAgKADgJQACgJAFgGQAFgHAIgEQAIgEALAAIAIABIAJAEIAIAGQAFADACAFIAAAAIAAgRIALAAIAABUQAAAKgCAIQgCAJgFAGQgFAGgIAFQgIADgNAAQgKAAgIgCgAgLg1QgGACgEAEQgEAFgDAHQgDAHABAIQgBAJACAIQACAGAEAHQAEAFAGAEQAGADAHAAQAIAAAGgDQAFgEAEgFQAEgFADgGQACgIAAgHQAAgIgCgIQgCgHgEgFQgEgGgGgDQgGgDgIAAQgFAAgGADg");
	this.shape_22.setTransform(327.05,-106.55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgGgGQgFgGgNAAQgEAAgEABQgEACgEADIgFAGIgEAGIgCAJIAAAJIAAAxIgLAAIAAhdIALAAIAAAOQAGgHAHgEQAHgFAJAAQAJAAAHADQAHADAGAIQADAFAAAFIABALIAAA8g");
	this.shape_23.setTransform(316.75,-108.45);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQAuQgIgDgGgGQgGgGgDgJQgDgKAAgMQAAgJACgJQADgJAFgHQAGgGAIgEQAIgEAKAAQALAAAIAEQAIAEAFAGQAGAHACAJQADAJAAAJQAAALgDAJQgDAJgGAHQgFAGgIAEQgIADgKAAQgIAAgIgDgAgOgjQgGADgDAGQgEAFgCAHIgCAOQAAAJACAHQACAHAEAGQAEAFAGADQAGADAHAAQAIAAAGgEQAGgDAEgGQAEgFACgHQABgHAAgIQAAgHgBgHQgCgIgEgFQgEgFgGgDQgGgDgIAAQgIAAgGADg");
	this.shape_24.setTransform(306.775,-108.325);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgEQAHgFAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAPIAAAtg");
	this.shape_25.setTransform(299.225,-108.45);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgDA5QgEgEAAgLIAAhDIgNAAIAAgJIANAAIAAgaIAKAAIAAAaIARAAIAAAJIgRAAIAAA/IAAAGIABAEQABAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIAFABIAFAAIAEgBIAAAJIgFABIgHABQgIAAgEgEg");
	this.shape_26.setTransform(293.25,-109.475);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgPAvQgHgDgEgEQgFgEgCgGQgCgGAAgGIAKAAQADAMAHAFQAGAFALAAQAGAAAEgCIAIgEQACgCABgDQACgDAAgEQAAgHgEgDQgEgDgHgCIgOgDIgOgEQgHgCgEgFQgFgFABgJQAAgMAIgIQAJgHAPAAQAOAAAKAHQAJAGACAQIgLAAQgBgLgHgEQgHgEgJAAQgKAAgFAEQgGAEAAAIQAAAGAFADQAEAEAHACIANADIAOAEQAHADAEAFQAFAFAAAJQAAAHgDAFQgDAFgFADQgFAEgHACQgHABgHAAQgJAAgGgCg");
	this.shape_27.setTransform(286.3,-108.325);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAQgGAAgGgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_28.setTransform(272.025,-108.325);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgPAvQgGgDgFgEQgEgEgDgGQgDgGAAgGIALAAQADAMAHAFQAGAFALAAQAGAAAFgCIAHgEQADgCAAgDQACgDAAgEQAAgHgEgDQgFgDgGgCIgNgDIgPgEQgHgCgEgFQgFgFABgJQgBgMAJgIQAJgHAPAAQAPAAAJAHQAKAGABAQIgLAAQgBgLgHgEQgHgEgJAAQgKAAgGAEQgFAEAAAIQAAAGAEADQAFAEAHACIANADIAPAEQAGADAEAFQAEAFAAAJQAAAHgCAFQgDAFgFADQgFAEgHACQgHABgHAAQgIAAgHgCg");
	this.shape_29.setTransform(257.3,-108.325);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgRAuQgIgEgGgHQgFgGgDgJQgCgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQABAHACAHQACAHADAFQAFAFAFADQAGADAHAAQALAAAHgGQAHgGADgKIAMAAQgBAHgEAFQgDAGgFAEQgFAFgGACQgHACgJAAQgKAAgIgDgAAegFQAAgHgCgGQgCgGgDgFQgDgEgHgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgCAGIgEANIA8AAIAAAAg");
	this.shape_30.setTransform(247.8,-108.325);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgEQAHgFAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAPIAAAtg");
	this.shape_31.setTransform(240.275,-108.45);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgEBBIAAhdIAJAAIAABdgAgFgwIAAgQIALAAIAAAQg");
	this.shape_32.setTransform(234.9,-110.125);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgSAtQgHgCgEgFQgDgFgCgGQgCgGAAgHIAAg9IALAAIAAA9QAAAMAFAGQAGAHAMAAQAGgBAGgDQAFgCAEgFQADgFACgGQACgGAAgIIAAgyIALAAIAABcIgLAAIAAgMIgFAFIgGAEIgIAEQgFACgFAAQgKAAgFgDg");
	this.shape_33.setTransform(227.9,-108.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAgBCIAAgzQgFAIgKAFQgIAEgKAAQgKAAgIgEQgHgEgGgHQgFgGgCgJQgDgIAAgKQAAgKADgJQACgJAFgHQAFgGAIgEQAIgEALAAIAIABIAJAEIAIAGQAFADACAFIAAAAIAAgRIALAAIAACBgAgNg0QgGADgEAGQgEAGgCAIQgCAHABAJQgBAJADAGQADAGAEAFQAEAFAGACQAGADAFAAQAIAAAGgEQAGgDAEgFQAEgFACgGQACgIAAgIQAAgIgCgHQgDgHgEgGQgEgFgFgDQgGgDgIAAQgHAAgGADg");
	this.shape_34.setTransform(217.25,-106.625);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgRAuQgJgEgFgHQgFgGgCgJQgDgJAAgKQAAgKADgJQADgJAGgHQAFgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhHAAQAAAHACAHQABAHAEAFQAFAFAGADQAFADAHAAQAKAAAIgGQAHgGADgKIAMAAQgBAHgEAFQgDAGgFAEQgFAFgGACQgHACgJAAQgKAAgIgDgAAegFQAAgHgCgGQgCgGgDgFQgDgEgHgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgCAGIgDANIA7AAIAAAAg");
	this.shape_35.setTransform(206.95,-108.325);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgEQAHgFAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAPIAAAtg");
	this.shape_36.setTransform(199.425,-108.45);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAaAwIAAg8QAAgNgGgGQgFgGgNAAQgEAAgEABQgEACgDADIgGAGIgEAGIgCAJIgBAJIAAAxIgKAAIAAhdIAKAAIAAAOQAHgHAHgEQAHgFAJAAQAIAAAIADQAHADAGAIQACAFABAFIABALIAAA8g");
	this.shape_37.setTransform(186,-108.45);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgQAuQgIgDgGgGQgGgGgDgJQgDgKAAgMQAAgJACgJQADgJAFgHQAGgGAIgEQAIgEAKAAQALAAAIAEQAIAEAFAGQAGAHACAJQADAJAAAJQAAALgDAJQgDAJgGAHQgFAGgIAEQgIADgKAAQgIAAgIgDgAgOgjQgGADgDAGQgEAFgCAHIgCAOQAAAJACAHQACAHAEAGQAEAFAGADQAGADAHAAQAIAAAGgEQAGgDAEgGQAEgFACgHQABgHAAgIQAAgHgBgHQgCgIgEgFQgEgFgGgDQgGgDgIAAQgIAAgGADg");
	this.shape_38.setTransform(176.025,-108.325);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgFBBIAAhdIAKAAIAABdgAgFgwIAAgQIALAAIAAAQg");
	this.shape_39.setTransform(169.05,-110.125);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgCA5QgFgEAAgLIAAhDIgNAAIAAgJIANAAIAAgaIAKAAIAAAaIASAAIAAAJIgSAAIAAA/IAAAGIACAEQAAAAAAABQAAAAAAAAQABABAAAAQABAAAAAAIAGABIAEAAIAEgBIAAAJIgFABIgHABQgJAAgCgEg");
	this.shape_40.setTransform(164.5,-109.475);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgYAwQgFgCgFgDQgEgEgCgFQgDgFAAgHQAAgWAhgFIAOgCIAHgBIAHgCQACgBABgDIABgFQAAgJgGgFQgFgFgLAAIgLABQgEABgEACQgDADgDAEQgCAEgBAGIgLAAQABgJADgFQADgGAGgEQAFgEAGgBQAHgCAIAAQAGAAAGACQAGABAFADQAEAEADAFQADAGAAAIIAAAyQAAAGACACQACABAHgCIAAAIIgEABIgFABIgEAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgDIgCgEIAAgFQgHAHgJAEQgIAEgKAAQgGAAgGgBgAAIACIgNABQgNABgHAFQgGAEAAAKQAAAEABADIAFAGIAGADIAIABQAGAAAFgCQAGgCAFgDQAFgDADgFQADgGAAgHIAAgNQgHACgHABg");
	this.shape_41.setTransform(157.275,-108.325);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgRAuQgIgEgFgHQgFgGgDgJQgDgJABgLQAAgIACgJQADgJAFgHQAGgHAIgEQAIgEAKAAQAQAAAJAIQAKAIADAQIgLAAQgDgLgHgFQgHgGgKAAQgIAAgGADQgGAEgDAFQgEAGgCAHQgCAHAAAGQAAAIABAHQACAHAEAFQAEAGAGADQAGAEAIAAQALAAAIgHQAHgHACgMIALAAQgBAIgDAHQgEAGgEAFQgFAEgHADQgHACgIAAQgLAAgIgDg");
	this.shape_42.setTransform(147.05,-108.325);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgTAtQgGgCgEgFQgEgFgCgGQgBgGAAgHIAAg9IAKAAIAAA9QABAMAFAGQAGAHANAAQAGgBAEgDQAGgCADgFQAEgFACgGQACgGAAgIIAAgyIALAAIAABcIgLAAIAAgMIgEAFIgHAEIgIAEQgFACgFAAQgJAAgHgDg");
	this.shape_43.setTransform(137.05,-108.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgTA+QgIgEgFgGQgFgHgDgJQgCgJAAgKQAAgJACgJQADgJAFgHQAGgGAHgEQAIgFALABQAJgBAJAFQAJAEAFAJIAAgzIALAAIAACAIgLAAIAAgQIgBAAQgCAFgDADQgEAEgEACIgJADIgJACQgLAAgIgEgAgNgSQgGADgEAGQgEAFgCAIQgCAHAAAIQAAAKADAGQACAHAFAFQAEAEAGADQAGADAFAAQAIAAAGgEQAGgDAEgFQAEgGACgGQACgIAAgJQAAgHgCgIQgCgFgEgGQgFgFgGgEQgFgCgIAAQgHgBgGAEg");
	this.shape_44.setTransform(126.4,-110);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgSAuQgIgEgFgHQgFgGgDgJQgCgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQAAAHACAHQACAHAEAFQAFAFAFADQAGADAHAAQALAAAHgGQAIgGACgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgHACQgGACgJAAQgKAAgJgDgAAfgFQAAgHgCgGQgCgGgEgFQgEgEgGgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgDAGIgDANIA9AAIAAAAg");
	this.shape_45.setTransform(116.1,-108.325);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgUAwIAAhdIALAAIAAASQAFgLAGgEQAHgFAMAAIAAAMQgJAAgGADQgGADgDAFQgDAGgCAGIgBAPIAAAtg");
	this.shape_46.setTransform(103.575,-108.45);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgRAuQgIgEgGgHQgFgGgDgJQgCgJAAgKQAAgKADgJQADgJAFgHQAGgGAIgEQAIgEAJAAQATAAALANQALANAAAZIhIAAQAAAHADAHQACAHADAFQAFAFAFADQAGADAHAAQALAAAHgGQAIgGACgKIAMAAQgCAHgDAFQgDAGgFAEQgFAFgGACQgHACgJAAQgKAAgIgDgAAegFQAAgHgBgGQgCgGgEgFQgDgEgHgDQgFgCgHAAQgGAAgGACQgFADgEAFQgEAEgCAGIgEANIA8AAIAAAAg");
	this.shape_47.setTransform(95.15,-108.325);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAaBBIAAg9QAAgMgFgGQgGgGgNAAQgEAAgEABQgFACgDACIgGAGIgDAHIgCAIIAAAJIAAAyIgLAAIAAiBIALAAIAAAyQAGgHAHgFQAHgEAJAAQAJAAAHADQAIADAEAHQADAFACAGIAAAKIAAA9g");
	this.shape_48.setTransform(85.15,-110.125);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgSBBQgHgDgEgEQgFgEgDgFQgDgFABgEIALAAQACAFACAEIAGAFQAEACAEABIAKAAQAKAAAGgDQAIgEACgGQAEgGABgIIABgQQgFAIgKAFQgIAEgKAAQgKAAgIgDQgHgFgGgHQgFgGgCgJQgDgIAAgKQAAgKADgJQACgJAFgGQAFgHAIgEQAIgEALAAIAIABIAJAEIAIAGQAEADADAFIAAAAIAAgRIALAAIAABUQAAAKgCAIQgCAJgFAGQgFAGgIAFQgJADgMAAQgKAAgIgCgAgLg1QgGACgEAEQgEAFgDAHQgDAHABAIQgBAJACAIQACAGAEAHQAEAFAGAEQAGADAHAAQAIAAAGgDQAGgEAEgFQADgFADgGQACgIAAgHQAAgIgCgIQgCgHgEgFQgEgGgGgDQgGgDgIAAQgFAAgGADg");
	this.shape_49.setTransform(74.5,-106.55);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgFBBIAAhdIAKAAIAABdgAgFgwIAAgQIALAAIAAAQg");
	this.shape_50.setTransform(67.25,-110.125);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AAmBBIAAhAIhLAAIAABAIgNAAIAAiBIANAAIAAA4IBLAAIAAg4IAMAAIAACBg");
	this.shape_51.setTransform(58.8,-110.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(41.8,-119.5,337.5,42.5), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhqECQgxgaghgvIBAgwQA3BEBJAAQArAAAbgUQAagVAAgjQAAgegXgTQgOgNgsgVIg8gcQg8gbgegeQgngnABg4QAAhCAygrQAygoBIAAQA2AAAsAXQAqAWAcAnIg/AvQgrg0g+AAQgjAAgWARQgZASAAAgQgBAcAWATQAOALApAUIA9AdQBDAeAeAhQAjAmAAA2QgBBIg0AsQgzArhRAAQg7AAg0gag");
	this.shape.setTransform(-222.85,-187.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhqECQgxgaghgvIA/gwQA4BEBJAAQArAAAagUQAagVABgjQgBgegWgTQgPgNgrgVIg9gcQg7gbgegeQgngoABg3QAAhCAygrQAygoBHAAQA2AAAtAXQAqAWAcAnIg/AvQgqg0hAAAQgiAAgWARQgZASAAAgQgBAcAWATQAOALApAUIA8AdQBDAeAfAhQAjAmAAA2QAABIg1AsQg0ArhQAAQg8AAgzgag");
	this.shape_1.setTransform(-456.85,-187.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhqECQgygagggvIA/gwQA4BEBJAAQAsAAAZgUQAbgVgBgjQABgegXgTQgPgNgrgVIg8gcQg8gbgegeQgngnAAg4QAAhCA0grQAwgoBJAAQA1AAAtAXQAqAWAcAnIg/AvQgrg0g+AAQgjAAgWARQgaASAAAgQAAAcAWATQAOALApAUIA9AdQBCAeAfAhQAiAmAAA2QABBIg1AsQg0ArhPAAQg9AAgzgag");
	this.shape_2.setTransform(-269.45,-187.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ai5ETIAAolIFpAAIAABPIkRAAIAACNIDNAAIAABLIjNAAIAACvIEbAAIAABPg");
	this.shape_3.setTransform(-318.775,-187.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ADFEcIlOl8IAAFzIhZAAIAAouIAfAAIFOF7IAAlyIBYAAIAAIug");
	this.shape_4.setTransform(-376.425,-187.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgrETIAAolIBXAAIAAIlg");
	this.shape_5.setTransform(-420.775,-187.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AihDbQhAhAAAhrIAAlGIBYAAIAAFMQAABFAoAoQAmAkA8AAQA8AAAlgkQAogoAAhFIAAlMIBYAAIAAFGQAABrhBBAQg9A8hjABQhkgBg+g8g");
	this.shape_6.setTransform(-510.225,-187.15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AjOETIAAolIDAAAQBKAAAtApQAuApgBBAQABBAgvAoQAxAQAbAjQAbAlAAAzQAABGgxAsQgxAuhQAAgAh4DGICNAAQAuAAAagYQAZgXAAgnQAAgngZgXQgagXguAAIiNAAgAh4gwIBiAAQAoAAAWgVQAWgUAAgiQAAgigWgTQgWgVgoABIhiAAg");
	this.shape_7.setTransform(-563.6,-187.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AlNHMQi+i/AAkNQAAkMC+i+QC/i/EMAAQBXAABUAXQBUAXBLAsQAxAdAOA4QAOA2gdAxQgdAxg3AOQg3AOgxgcQhYg1hmAAQibAAhuBuQhuBvAACaQAACcBuBtQBuBuCbAAQBmABBYg0QAxgdA3ANQA3APAdAxQAdAwgOA4QgOA3gxAdQhLAshUAXQhUAXhXAAQkMAAi/i+g");
	this.shape_8.setTransform(-540.5471,-318.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AnLHMQi+i/AAkNQAAkMC+i+QC/i/EMAAQENAAC+C/QC/C+AAEMQAAENi/C/Qi+C+kNAAQkMAAi/i+gAkIkJQhvBvAACaQAACcBvBtQBuBuCaAAQCbAABvhuQBuhtAAicQAAiahuhvQhvhuibAAQiaAAhuBug");
	this.shape_9.setTransform(-401.65,-318.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AGnJwQg5gDgmgrIlIlzIlHFzQgmArg4ADQg6AEgqgmQgrgmgDg4QgEg5AmgqIFfmNIlfmLQgmgrAEg4QADg6ArglQAqgmA6ADQA4AEAmArIFHFzIFIlzQAmgrA5gEQA5gDAqAmQAqAlAEA6QADA4glArIlfGLIFfGNQAlAqgDA5QgEA4gqAmQgnAjgzAAIgJgBg");
	this.shape_10.setTransform(-257.15,-318.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-592.9,-383.9,392.59999999999997,224.7), null);


(lib.invisoButton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-364,-45,728,90);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkAxIAAhhIBGAAIAAASIgyAAIAAAUIAuAAIAAAQIguAAIAAAZIA1AAIAAASg");
	this.shape.setTransform(38.525,-15.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AARAxIgBgGIgBgIIAAgJQAAgKgDgCQgDgDgJAAIgTAAIAAAmIgUAAIAAhhIAuAAQAKABAFACQAGACADAEIAFAJQACAFAAAFQAAAHgDAHQgEAGgIACQAHADADAFQACAFAAAKIAAAHIABAJQABADADACIAAADgAgTgEIAVAAQAHAAADgCQAGgDAAgIQAAgJgGgDQgDgCgGAAIgWAAg");
	this.shape_1.setTransform(29.075,-15.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgfAoQgPgOAAgaQAAgaAPgNQALgLAUAAQAVAAALALQAPANAAAaQAAAagPAOQgLALgVAAQgUAAgLgLgAgSgYQgHAJAAAPQAAAQAHAJQAHAJALAAQAMAAAHgJQAHgJAAgQQAAgPgHgJQgHgJgMAAQgLAAgHAJg");
	this.shape_2.setTransform(18.875,-15.875);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcAxIAAhBIAAgIIAAgIIgSBRIgTAAIgShRIAAAIIAAAIIAABBIgTAAIAAhhIAdAAIARBLIAShLIAdAAIAABhg");
	this.shape_3.setTransform(8.05,-15.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AATAxIgmhFIAABFIgTAAIAAhhIAVAAIAmBDIAAhDIASAAIAABhg");
	this.shape_4.setTransform(-6.175,-15.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AARAxIgBgGIgBgIIAAgJQAAgKgDgCQgDgDgJAAIgTAAIAAAmIgUAAIAAhhIAuAAQAKABAFACQAGACADAEIAFAJQACAFAAAFQAAAHgDAHQgEAGgIACQAHADADAFQACAFAAAKIAAAHIABAJQABADADACIAAADgAgTgEIAVAAQAHAAADgCQAGgDAAgIQAAgJgGgDQgDgCgGAAIgWAAg");
	this.shape_5.setTransform(-15.775,-15.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAYAxIgGgUIgjAAIgHAUIgVAAIAihhIAXAAIAiBhgAAMAMIgMgmIgMAmIAYAAg");
	this.shape_6.setTransform(-25.55,-15.85);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgkAxIAAhhIBGAAIAAASIgyAAIAAAUIAuAAIAAAQIguAAIAAAZIA1AAIAAASg");
	this.shape_7.setTransform(-34.725,-15.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AghAxIAAhhIAUAAIAABPIAvAAIAAASg");
	this.shape_8.setTransform(-43.225,-15.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_2
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0F155B").s().p("AmoCvQhIAAg0gzQgzgzAAhJQAAhIAzgzQA0gzBIAAINRAAQBIAAA0AzQAzAzAABIQAABJgzAzQg0AzhIAAg");
	this.shape_9.setTransform(-2.75,-16.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-72.5,-34,140.1,35), null);


(lib.BG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_358 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(358).call(this.frame_358).wait(1));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0099DF","#003087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape.setTransform(364,45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#0098DE","#003087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_1.setTransform(364,45);
	this.shape_1._off = true;

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#0197DD","#003087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_2.setTransform(364,45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#0196DD","#013087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_3.setTransform(364,45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#0195DC","#013087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_4.setTransform(364,45);
	this.shape_4._off = true;

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#0294DB","#013087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_5.setTransform(364,45);
	this.shape_5._off = true;

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#0294DA","#013087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_6.setTransform(364,45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#0293DA","#023087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_7.setTransform(364,45);
	this.shape_7._off = true;

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#0392D9","#023087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_8.setTransform(364,45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#0391D8","#023088"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_9.setTransform(364,45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#0390D7","#023088"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_10.setTransform(364,45);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#048FD7","#033088"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_11.setTransform(364,45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#048ED6","#033188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_12.setTransform(364,45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#048DD5","#033188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_13.setTransform(364,45);
	this.shape_13._off = true;

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#058CD4","#033188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_14.setTransform(364,45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#058BD4","#043188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_15.setTransform(364,45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#058AD3","#043188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_16.setTransform(364,45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#0689D2","#043188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_17.setTransform(364,45);
	this.shape_17._off = true;

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#0689D1","#043188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_18.setTransform(364,45);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#0688D1","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_19.setTransform(364,45);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#0787D0","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_20.setTransform(364,45);
	this.shape_20._off = true;

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#0786CF","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_21.setTransform(364,45);
	this.shape_21._off = true;

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.lf(["#0785CE","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_22.setTransform(364,45);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.lf(["#0884CE","#063188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_23.setTransform(364,45);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#0883CD","#063188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_24.setTransform(364,45);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#0882CC","#063188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_25.setTransform(364,45);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.lf(["#0981CB","#063188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_26.setTransform(364,45);
	this.shape_26._off = true;

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.lf(["#0980CA","#063189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_27.setTransform(364,45);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.lf(["#097FCA","#073189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_28.setTransform(364,45);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.lf(["#0A7EC9","#073189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_29.setTransform(364,45);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.lf(["#0A7EC8","#073189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_30.setTransform(364,45);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.lf(["#0A7DC7","#073189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_31.setTransform(364,45);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.lf(["#0B7CC7","#083189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_32.setTransform(364,45);
	this.shape_32._off = true;

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.lf(["#0B7BC6","#083189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_33.setTransform(364,45);
	this.shape_33._off = true;

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.lf(["#0B7AC5","#083189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_34.setTransform(364,45);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.lf(["#0C79C4","#083189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_35.setTransform(364,45);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.lf(["#0C78C4","#093289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_36.setTransform(364,45);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.lf(["#0D77C3","#093289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_37.setTransform(364,45);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.lf(["#0D76C2","#093289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_38.setTransform(364,45);
	this.shape_38._off = true;

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.lf(["#0D75C1","#093289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_39.setTransform(364,45);
	this.shape_39._off = true;

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.lf(["#0E74C1","#0A3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_40.setTransform(364,45);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.lf(["#0E73C0","#0A3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_41.setTransform(364,45);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.lf(["#0E73BF","#0A3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_42.setTransform(364,45);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.lf(["#0F72BE","#0A3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_43.setTransform(364,45);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.lf(["#0F71BE","#0B3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_44.setTransform(364,45);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.lf(["#0F70BD","#0B328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_45.setTransform(364,45);
	this.shape_45._off = true;

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.lf(["#106FBC","#0B328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_46.setTransform(364,45);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.lf(["#106EBB","#0B328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_47.setTransform(364,45);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.lf(["#106DBA","#0B328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_48.setTransform(364,45);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.lf(["#116CBA","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_49.setTransform(364,45);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.lf(["#116BB9","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_50.setTransform(364,45);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.lf(["#116AB8","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_51.setTransform(364,45);
	this.shape_51._off = true;

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.lf(["#1269B7","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_52.setTransform(364,45);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.lf(["#1268B7","#0D328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_53.setTransform(364,45);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.lf(["#1268B6","#0D328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_54.setTransform(364,45);
	this.shape_54._off = true;

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.lf(["#1367B5","#0D328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_55.setTransform(364,45);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.lf(["#1366B4","#0D328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_56.setTransform(364,45);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.lf(["#1365B4","#0E328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_57.setTransform(364,45);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.lf(["#1464B3","#0E328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_58.setTransform(364,45);
	this.shape_58._off = true;

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.lf(["#1463B2","#0E328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_59.setTransform(364,45);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.lf(["#1462B1","#0E338A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_60.setTransform(364,45);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.lf(["#1561B1","#0F338A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_61.setTransform(364,45);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.lf(["#1560B0","#0F338A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_62.setTransform(364,45);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.lf(["#155FAF","#0F338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_63.setTransform(364,45);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.lf(["#165EAE","#0F338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_64.setTransform(364,45);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.lf(["#165DAE","#10338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_65.setTransform(364,45);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.lf(["#165DAD","#10338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_66.setTransform(364,45);
	this.shape_66._off = true;

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.lf(["#175CAC","#10338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_67.setTransform(364,45);
	this.shape_67._off = true;

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.lf(["#175BAB","#10338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_68.setTransform(364,45);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.lf(["#175AAB","#11338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_69.setTransform(364,45);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.lf(["#1859AA","#11338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_70.setTransform(364,45);
	this.shape_70._off = true;

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.lf(["#1858A9","#11338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_71.setTransform(364,45);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.lf(["#175AAA","#11338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_72.setTransform(364,45);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.lf(["#175AAB","#10338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_73.setTransform(364,45);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.lf(["#175BAC","#10338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_74.setTransform(364,45);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.lf(["#165CAD","#10338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_75.setTransform(364,45);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.lf(["#165FAF","#0F338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_76.setTransform(364,45);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.lf(["#1560AF","#0F338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_77.setTransform(364,45);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.lf(["#1560B0","#0F338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_78.setTransform(364,45);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.lf(["#1561B0","#0F338A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_79.setTransform(364,45);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.lf(["#1462B2","#0E338A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_80.setTransform(364,45);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.lf(["#1463B2","#0E338A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_81.setTransform(364,45);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.lf(["#1365B3","#0E328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_82.setTransform(364,45);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.lf(["#1365B4","#0D328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_83.setTransform(364,45);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.lf(["#1366B5","#0D328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_84.setTransform(364,45);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.lf(["#1267B6","#0D328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_85.setTransform(364,45);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.lf(["#1269B7","#0D328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_86.setTransform(364,45);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.lf(["#1269B8","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_87.setTransform(364,45);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.lf(["#116CB9","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_88.setTransform(364,45);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.lf(["#106DBA","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_89.setTransform(364,45);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.lf(["#106DBB","#0B328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_90.setTransform(364,45);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.lf(["#106EBC","#0B328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_91.setTransform(364,45);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.lf(["#0F6FBC","#0B328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_92.setTransform(364,45);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.lf(["#0F71BD","#0B3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_93.setTransform(364,45);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.lf(["#0F71BE","#0A3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_94.setTransform(364,45);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.lf(["#0E72BF","#0A3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_95.setTransform(364,45);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.lf(["#0E74C0","#0A3289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_96.setTransform(364,45);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.lf(["#0C77C3","#093289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_97.setTransform(364,45);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.lf(["#0C78C3","#093289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_98.setTransform(364,45);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.lf(["#0C79C5","#083189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_99.setTransform(364,45);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.lf(["#0C7AC5","#083189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_100.setTransform(364,45);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.lf(["#0A7DC8","#073189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_101.setTransform(364,45);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.lf(["#0A7FC9","#073189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_102.setTransform(364,45);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.lf(["#0980CA","#073189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_103.setTransform(364,45);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.lf(["#0980CB","#063189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_104.setTransform(364,45);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.lf(["#0982CC","#063188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_105.setTransform(364,45);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.lf(["#0883CC","#063188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_106.setTransform(364,45);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.lf(["#0884CD","#063188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_107.setTransform(364,45);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.lf(["#0884CE","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_108.setTransform(364,45);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.lf(["#0785CF","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_109.setTransform(364,45);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.lf(["#0688D0","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_110.setTransform(364,45);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.lf(["#0688D1","#043188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_111.setTransform(364,45);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.lf(["#068AD2","#043188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_112.setTransform(364,45);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.lf(["#058BD3","#043188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_113.setTransform(364,45);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.lf(["#058CD4","#043188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_114.setTransform(364,45);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.lf(["#058CD5","#033188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_115.setTransform(364,45);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.lf(["#048ED6","#033088"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_116.setTransform(364,45);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.lf(["#048FD6","#033088"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_117.setTransform(364,45);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.lf(["#0390D8","#023088"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_118.setTransform(364,45);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.lf(["#0391D8","#023087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_119.setTransform(364,45);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.lf(["#0391D9","#023087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_120.setTransform(364,45);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.lf(["#0292D9","#023087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_121.setTransform(364,45);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.lf(["#0295DB","#013087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_122.setTransform(364,45);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.lf(["#0196DC","#013087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_123.setTransform(364,45);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.lf(["#0197DD","#013087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_124.setTransform(364,45);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.lf(["#0197DE","#003087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_125.setTransform(364,45);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.lf(["#165EAE","#10338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_126.setTransform(364,45);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.lf(["#165FAE","#0F338B"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_127.setTransform(364,45);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.lf(["#116BB8","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_128.setTransform(364,45);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.lf(["#106CBA","#0C328A"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_129.setTransform(364,45);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.lf(["#0D77C2","#093289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_130.setTransform(364,45);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.lf(["#0C79C4","#093289"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_131.setTransform(364,45);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.lf(["#0B7AC6","#083189"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_132.setTransform(364,45);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.lf(["#0885CE","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_133.setTransform(364,45);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.lf(["#0786D0","#053188"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_134.setTransform(364,45);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.lf(["#0293DA","#013087"],[0,1],-364,0,364,0).s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_135.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_72}]},1).to({state:[{t:this.shape_73}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_74}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_75}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_76}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_77}]},1).to({state:[{t:this.shape_78}]},1).to({state:[{t:this.shape_79}]},1).to({state:[{t:this.shape_79}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_80}]},1).to({state:[{t:this.shape_81}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_82}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_83}]},1).to({state:[{t:this.shape_84}]},1).to({state:[{t:this.shape_84}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_85}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_86}]},1).to({state:[{t:this.shape_86}]},1).to({state:[{t:this.shape_87}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_88}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_89}]},1).to({state:[{t:this.shape_90}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_91}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_92}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_93}]},1).to({state:[{t:this.shape_94}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_95}]},1).to({state:[{t:this.shape_95}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_96}]},1).to({state:[{t:this.shape_96}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_97}]},1).to({state:[{t:this.shape_98}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_99}]},1).to({state:[{t:this.shape_100}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_101}]},1).to({state:[{t:this.shape_101}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_102}]},1).to({state:[{t:this.shape_102}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_103}]},1).to({state:[{t:this.shape_104}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_105}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_106}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_107}]},1).to({state:[{t:this.shape_108}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_109}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_110}]},1).to({state:[{t:this.shape_111}]},1).to({state:[{t:this.shape_111}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_112}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_113}]},1).to({state:[{t:this.shape_113}]},1).to({state:[{t:this.shape_114}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_115}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_116}]},1).to({state:[{t:this.shape_117}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_118}]},1).to({state:[{t:this.shape_118}]},1).to({state:[{t:this.shape_119}]},1).to({state:[{t:this.shape_120}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_121}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_122}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_123}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_124}]},1).to({state:[{t:this.shape_125}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_126}]},1).to({state:[{t:this.shape_127}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_84}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_86}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_128}]},1).to({state:[{t:this.shape_88}]},1).to({state:[{t:this.shape_129}]},1).to({state:[{t:this.shape_90}]},1).to({state:[{t:this.shape_91}]},1).to({state:[{t:this.shape_92}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_94}]},1).to({state:[{t:this.shape_95}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_96}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_130}]},1).to({state:[{t:this.shape_98}]},1).to({state:[{t:this.shape_131}]},1).to({state:[{t:this.shape_99}]},1).to({state:[{t:this.shape_132}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_101}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_102}]},1).to({state:[{t:this.shape_103}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_105}]},1).to({state:[{t:this.shape_106}]},1).to({state:[{t:this.shape_107}]},1).to({state:[{t:this.shape_133}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_134}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_111}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_113}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_135}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(214).to({_off:false},0).wait(2).to({_off:true},1).wait(140).to({_off:false},0).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1).to({_off:false},0).to({_off:true},1).wait(211).to({_off:false},0).wait(1).to({_off:true},1).wait(3).to({_off:false},0).to({_off:true},1).wait(138).to({_off:false},0).to({_off:true},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(4).to({_off:false},0).to({_off:true},1).wait(202).to({_off:false},0).wait(1).to({_off:true},1).wait(12).to({_off:false},0).to({_off:true},1).wait(132).to({_off:false},0).to({_off:true},1).wait(4));
	this.timeline.addTween(cjs.Tween.get(this.shape_5).wait(5).to({_off:false},0).to({_off:true},1).wait(198).to({_off:false},0).wait(1).to({_off:true},1).wait(16).to({_off:false},0).to({_off:true},1).wait(130).to({_off:false},0).to({_off:true},1).wait(5));
	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(7).to({_off:false},0).to({_off:true},1).wait(194).to({_off:false},0).wait(1).to({_off:true},1).wait(20).to({_off:false},0).to({_off:true},1).wait(126).to({_off:false},0).to({_off:true},1).wait(7));
	this.timeline.addTween(cjs.Tween.get(this.shape_13).wait(13).to({_off:false},0).to({_off:true},1).wait(175).to({_off:false},0).wait(1).to({_off:true},1).wait(39).to({_off:false},0).to({_off:true},1).wait(114).to({_off:false},0).to({_off:true},1).wait(13));
	this.timeline.addTween(cjs.Tween.get(this.shape_17).wait(17).to({_off:false},0).to({_off:true},1).wait(162).to({_off:false},0).wait(1).to({_off:true},1).wait(52).to({_off:false},0).to({_off:true},1).wait(106).to({_off:false},0).to({_off:true},1).wait(17));
	this.timeline.addTween(cjs.Tween.get(this.shape_20).wait(20).to({_off:false},0).to({_off:true},1).wait(154).to({_off:false},0).wait(1).to({_off:true},1).wait(60).to({_off:false},0).to({_off:true},1).wait(101).to({_off:false},0).to({_off:true},1).wait(19));
	this.timeline.addTween(cjs.Tween.get(this.shape_21).wait(21).to({_off:false},0).to({_off:true},1).wait(151).to({_off:false},0).wait(1).to({_off:true},1).wait(63).to({_off:false},0).to({_off:true},1).wait(98).to({_off:false},0).to({_off:true},1).wait(21));
	this.timeline.addTween(cjs.Tween.get(this.shape_26).wait(26).to({_off:false},0).to({_off:true},1).wait(135).to({_off:false},0).wait(1).to({_off:true},1).wait(79).to({_off:false},0).to({_off:true},1).wait(88).to({_off:false},0).to({_off:true},1).wait(26));
	this.timeline.addTween(cjs.Tween.get(this.shape_32).wait(32).to({_off:false},0).to({_off:true},1).wait(118).to({_off:false},0).wait(1).to({_off:true},1).wait(96).to({_off:false},0).to({_off:true},1).wait(77).to({_off:false},0).to({_off:true},1).wait(31));
	this.timeline.addTween(cjs.Tween.get(this.shape_33).wait(33).to({_off:false},0).to({_off:true},1).wait(114).to({_off:false},0).wait(2).to({_off:true},1).wait(99).to({_off:false},0).to({_off:true},1).wait(75).to({_off:false},0).to({_off:true},1).wait(32));
	this.timeline.addTween(cjs.Tween.get(this.shape_38).wait(38).to({_off:false},0).to({_off:true},1).wait(98).to({_off:false},0).wait(2).to({_off:true},1).wait(115).to({_off:false},0).to({_off:true},1).wait(64).to({_off:false},0).to({_off:true},1).wait(38));
	this.timeline.addTween(cjs.Tween.get(this.shape_39).wait(39).to({_off:false},0).to({_off:true},1).wait(95).to({_off:false},0).wait(1).to({_off:true},1).wait(119).to({_off:false},0).to({_off:true},1).wait(62).to({_off:false},0).to({_off:true},1).wait(39));
	this.timeline.addTween(cjs.Tween.get(this.shape_45).wait(45).to({_off:false},0).to({_off:true},1).wait(78).to({_off:false},0).wait(1).to({_off:true},1).wait(136).to({_off:false},0).to({_off:true},1).wait(51).to({_off:false},0).to({_off:true},1).wait(44));
	this.timeline.addTween(cjs.Tween.get(this.shape_51).wait(51).to({_off:false},0).to({_off:true},1).wait(59).to({_off:false},0).wait(1).to({_off:true},1).wait(155).to({_off:false},0).to({_off:true},1).wait(38).to({_off:false},0).to({_off:true},1).wait(51));
	this.timeline.addTween(cjs.Tween.get(this.shape_54).wait(54).to({_off:false},0).to({_off:true},1).wait(51).to({_off:false},0).wait(1).to({_off:true},1).wait(163).to({_off:false},0).to({_off:true},1).wait(33).to({_off:false},0).to({_off:true},1).wait(53));
	this.timeline.addTween(cjs.Tween.get(this.shape_58).wait(58).to({_off:false},0).to({_off:true},1).wait(38).to({_off:false},0).wait(1).to({_off:true},1).wait(176).to({_off:false},0).to({_off:true},1).wait(25).to({_off:false},0).to({_off:true},1).wait(57));
	this.timeline.addTween(cjs.Tween.get(this.shape_66).wait(66).to({_off:false},0).to({_off:true},1).wait(15).to({_off:false},0).wait(1).to({_off:true},1).wait(199).to({_off:false},0).to({_off:true},1).wait(9).to({_off:false},0).to({_off:true},1).wait(65));
	this.timeline.addTween(cjs.Tween.get(this.shape_67).wait(67).to({_off:false},0).to({_off:true},1).wait(11).to({_off:false},0).wait(1).to({_off:true},1).wait(203).to({_off:false},0).to({_off:true},1).wait(7).to({_off:false},0).to({_off:true},1).wait(66));
	this.timeline.addTween(cjs.Tween.get(this.shape_70).wait(70).to({_off:false},0).to({_off:true},1).wait(2).to({_off:false},0).wait(1).to({_off:true},1).wait(212).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false},0).to({_off:true},1).wait(69));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


// stage content:
(lib.Cox_NE_Higher_Ed_728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var tl = new TimelineMax({repeat:0, repeatDelay:1});
		
		
		tl.from(this.txt1, .25, {alpha:0}, 1);
		tl.from(this.txt2, .25, {alpha:0}, "+=3");
		
		tl.to(this.txt2, .25, {alpha:0}, "+=3");
		tl.to(this.txt1, .25, {alpha:0}, "-=.25");
		
		tl.from(this.txt3, .25, {alpha:0}, "+=.25");
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(23).call(this.frame_23).wait(1));

	// invisoButton
	this.hotSpot = new lib.invisoButton();
	this.hotSpot.name = "hotSpot";
	this.hotSpot.parent = this;
	this.hotSpot.setTransform(364,45);
	new cjs.ButtonHelper(this.hotSpot, 0, 1, 2, false, new lib.invisoButton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.hotSpot).wait(24));

	// logo
	this.logo = new lib.logo();
	this.logo.name = "logo";
	this.logo.parent = this;
	this.logo.setTransform(665.5,44.8,0.18,0.18,0,0,0,-403.1,-276.7);
	this.logo.cache(-595,-386,397,229);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(24));

	// txt3
	this.txt3 = new lib.txt3();
	this.txt3.name = "txt3";
	this.txt3.parent = this;
	this.txt3.setTransform(328.75,121.75);

	this.timeline.addTween(cjs.Tween.get(this.txt3).wait(24));

	// txt2
	this.txt2 = new lib.txt2();
	this.txt2.name = "txt2";
	this.txt2.parent = this;
	this.txt2.setTransform(150.75,132);

	this.timeline.addTween(cjs.Tween.get(this.txt2).wait(24));

	// txt1
	this.txt1 = new lib.txt1();
	this.txt1.name = "txt1";
	this.txt1.parent = this;
	this.txt1.setTransform(150,132);

	this.timeline.addTween(cjs.Tween.get(this.txt1).wait(24));

	// cta
	this.cta = new lib.cta();
	this.cta.name = "cta";
	this.cta.parent = this;
	this.cta.setTransform(93.6,61.25);

	this.timeline.addTween(cjs.Tween.get(this.cta).wait(24));

	// BG
	this.instance = new lib.BG();
	this.instance.parent = this;
	this.instance.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(24));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(364,45,364,45);
// library properties:
lib.properties = {
	id: 'D91EC88F6BC042E595A6BC42B70CDE19',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['D91EC88F6BC042E595A6BC42B70CDE19'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;